# Generated by Django 3.1.1 on 2020-09-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body_part', models.IntegerField(choices=[(1, 'Chest'), (2, 'Bicep'), (3, 'Shoulders'), (4, 'Calfs'), (5, 'Hastrings'), (6, 'Quadriceps'), (7, 'Triceps')])),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Normal'), (3, 'Hard')])),
                ('notes', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
