# Generated by Django 3.1.1 on 2020-09-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200925_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(unique=True),
        ),
    ]
