# Generated by Django 3.1.1 on 2020-09-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200925_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateField(unique=True),
        ),
    ]
