# Generated by Django 3.1.1 on 2020-09-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200925_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['workout_date']},
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='created_at',
            new_name='workout_date',
        ),
    ]
