# Generated by Django 3.1.1 on 2020-09-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200925_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
