# Generated by Django 3.1.1 on 2020-09-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_set_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='user',
        ),
    ]
