# Generated by Django 3.1.1 on 2020-09-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_set_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='sets',
            field=models.ManyToManyField(blank=True, through='core.Set', to='core.Exercise'),
        ),
    ]
