# Generated by Django 3.1.1 on 2020-09-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200926_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='father_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='core.set'),
        ),
    ]
