# Generated by Django 3.1.1 on 2020-10-03 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200926_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateField(),
        ),
    ]
