# Generated by Django 3.1.1 on 2020-10-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201004_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
