# Generated by Django 3.1.1 on 2020-10-07 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_exercise_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
                ('routine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.routineday')),
            ],
        ),
        migrations.AlterField(
            model_name='routineday',
            name='sets',
            field=models.ManyToManyField(blank=True, through='core.SetRoutine', to='core.Exercise'),
        ),
    ]
