# Generated by Django 3.1.1 on 2020-10-07 02:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201007_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='routine',
        ),
        migrations.AlterField(
            model_name='set',
            name='work_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workout'),
        ),
        migrations.AlterField(
            model_name='setroutine',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.routineday'),
        ),
        migrations.CreateModel(
            name='SerieRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('comment', models.TextField(blank=True)),
                ('rpe', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('father_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='core.setroutine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
