# Generated by Django 3.1.1 on 2020-10-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_routineday_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineday',
            name='day',
        ),
        migrations.AddField(
            model_name='routineday',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
