# Generated by Django 3.1.1 on 2020-10-10 05:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201008_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='body_part',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'CHEST'), (2, 'BICEP'), (3, 'CALFS'), (4, 'HASTRINGS'), (5, 'QUADRICEPS'), (6, 'FEMORALS'), (7, 'SHOULDERS'), (8, 'GLUTEUS'), (8, 'BACK')], max_length=17),
        ),
    ]
